package bindx;

/**
 * @author deep <system.grand@gmail.com>
 */

import bindx.BindSignal;

@:autoBuild(bindx.BindMacros.build())
interface IBindable
{
	public var __fieldBindings__:FieldsBindSignal; // autogenerated field
	public var __methodBindings__:MethodsBindSignal; // autogenerated field
}