package bindx;

/**
 * ...
 * @author deep <system.grand@gmail.com>
 */

@:autoBuild(bindx.BindMacros.build())
interface IBindable
{
	public var __fieldBindings__:BindSignal; // autogenerated field
	public var __methodBindings__:BindSignal; // autogenerated field
}